name: Python unit tests

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ./Models/requirements.txt ]; then pip install -r ./Models/requirements.txt; fi
      - name: Run tests
        run: |
          python -m unittest discover -s ./Models/U2U -p '*test*.py' -v
      - name: Safety check
        run: |
          safety check -r ./Models/requirements.txt
